import { Car, User } from './types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alexander Sterling',
  email: 'alex@zenith.com',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100',
  verified: true,
  plan: 'Diamond',
  role: 'Customer',
};

export const MOCK_CARS: Car[] = [
  {
    id: 'c1',
    make: 'Porsche',
    model: '911 Carrera S',
    year: 2023,
    price: 135000,
    mileage: 1200,
    location: 'Beverly Hills, CA',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    type: 'Coupe',
    transmission: 'Automatic',
    fuelType: 'Gas',
    description: 'Prisinte condition, one owner. Extended warranty included.',
    vin: 'WP0AA2A9XPS2',
    status: 'Available',
    sellerName: 'Zenith Certified',
  },
  {
    id: 'c2',
    make: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    price: 94000,
    mileage: 500,
    location: 'Austin, TX',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad422432bd?auto=format&fit=crop&q=80&w=800',
    type: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Electric',
    description: 'The world\'s quickest accelerating production car.',
    vin: '5YJSA1E4XPF',
    status: 'Available',
    sellerName: 'Elon M.',
  },
  {
    id: 'c3',
    make: 'Land Rover',
    model: 'Range Rover SV',
    year: 2023,
    price: 185000,
    mileage: 3500,
    location: 'Miami, FL',
    image: 'https://images.unsplash.com/photo-1606148334078-434e791e860b?auto=format&fit=crop&q=80&w=800',
    type: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    description: 'Ultimate luxury with off-road capability. Bespoke interior.',
    vin: 'SALYA2B4XP',
    status: 'Pending',
    sellerName: 'Luxury Auto Group',
  },
  {
    id: 'c4',
    make: 'Mercedes-Benz',
    model: 'G 63 AMG',
    year: 2022,
    price: 198000,
    mileage: 8200,
    location: 'New York, NY',
    image: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&q=80&w=800',
    type: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gas',
    description: 'Iconic design with legendary performance.',
    vin: 'W1N4J5KB1NP',
    status: 'Available',
    sellerName: 'Elite Motors',
  }
];
